name = "dec-production-event-cron"
main = "src/index.ts"
compatibility_date = "2024-01-07"

[triggers]
crons = ["0 9 * * *"]

[[kv_namespaces]]
binding = "CRON_LOCK"
id = "94da48c698ef448c8c29ed276dc5ea77"
preview_id = "94da48c698ef448c8c29ed276dc5ea77"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true